### PR TITLE
Close simulator in tests and examples

### PR DESCRIPTION
**Pull request by tbekolay**
Still a work in progress, but thought it might be useful as something concrete for the #931 discussion.

This uses the simulator as a context manager in Nengo tests, and closes open simulators when the process ends. It raises a warning if it does this (which is controversial; we'll leave discussion of that to #931?).

It doesn't do `__del__`, because it's impossible to delete a simulator without closing it, since we keep track of open simulators in `nengo.Simulator.open_sims`.

Note that this is necessary for `nengo_spinnaker` to run unit tests.

Still to do:

- [x] Use sim as context manager in examples (this is causing the new `test_simulator` tests to fail at the moment)
- [x] Change things as a result of discussion in #931

### CODE REVIEW

**Comment by tbekolay** [comment]
This PR's been updated to close simulators in examples also. I must be missing something though, as the test of `close_open_sims` ([L97](https://github.com/nengo/nengo/commit/f140fc1c87ed11b5d90dceefc4e500ee5be1d2bf#diff-cf86547944b52ff847e0d9456cc3e7beR97) has 13 open sims if I don't close them all at the start of the test.

In any case, this passes tests locally, so will hopefully also pass on TravisCI. This PR also automatically closes all simualtors at exit; it currently warns if this happens, but that's still up in the air depending on discussion in #931. These changes are in f140fc1c87ed11b.

**Comment by tbekolay** [comment]
I've rebased this to master and pulled out the warning into a separate PR, as per the meeting (see #962). Ready for review!

**Comment by hunse** [comment]
LGTM. I think it's as advertised, and just changing the examples and tests to use `with` blocks, right? There's nothing else I should be looking for?

On a related note, I tried out the `with` block with different types of errors, and it works as we expected I think. If there's an error during build, the simulator `with` block never gets entered, so the simulator is not closed. If there's an error during running (e.g. a node returns `None` unexpectedly), then the simulator does get closed. So that's a good reason to use `with` blocks over the `.close()` method whenever possible.

@tcstewar, what happens on `nengo_spinnaker` when there's an error during build? Does all the memory get properly freed?

**Comment by tbekolay** [comment]
> just changing the examples and tests to use with blocks, right?

Yes, the only other changes are several instances where we either had `Simulator` in the args list but didn't make a `Simulator` instance, or one instance of using `nengo.Simulator` directly. They were obvious here since I was grepping all files for instances of `Simulator`.

**Comment by hunse** [comment]
> the only other changes are several instances where we either had `Simulator` in the args list but didn't make a `Simulator` instance, and one instance of using `nengo.Simulator` directly. They were obvious here since I was grepping all files for instances of `Simulator`.

Would it be possible to add static checks for this? Does `flake8` allow that somehow? The latter wouldn't be too hard to do with our own script, since `nengo.Simulator` should never appear in any of the test files, but checking that all arguments to test functions are used would be difficult.

**Comment by tbekolay** [comment]
> Would it be possible to add static checks for this?

Hmm... it's definitely possible; I am surprised PyFlakes doesn't already do this, as it will complain for other locally scoped variables that don't get used. But not arguments, for some reason. I believe that PyLint would pick up this, but PyLint emits a lot of issues for Nengo ATM so updating the code to pass PyLint would take some time (I tried to do it at one point).

If we want to just add this, or any other minor style thing, we can actually write our own tool that integrates with `flake8`, as `flake8` allows plugins to emit error codes through a `setuptools` entry point. That's something I've had in the back of my mind for a while but haven't put the time into doing it yet. See the [extending flake8 document](http://flake8.readthedocs.org/en/latest/extensions.html).

**Comment by hunse** [comment]
I added an issue for that static checking, and found two more instances of `nengo.Simulator` in the tests, and a few Simulator instances that weren't closed. So I think this is good to go now.

Can we get a second reviewer and/or merger? We've kind of gotten out of the random reviewer selection system. @tbekolay, would it help you out if we picked some random reviewers to get some of this stuff reviewed?

**Comment by tbekolay** [comment]
I stopped doing random people as it's an unnecessary burden for lab members who are busy with other things, so I've been favouring ABR reviewers whenever no one volunteers. Which means @drasmuss!

**Comment by drasmuss** [comment]
Looks good to me

**Pull request merged**
