### PR TITLE
Added option to not normalize encoders

### PR DESCRIPTION
**Pull request by bmorcos**
**Motivation and context:**
Functionality requested in #1191 

**How has this been tested?**
Added a new test

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**

- New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- N/A I have updated the documentation accordingly. (probably N/A?)
- [x] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Still to do:**

### CODE REVIEW

**Comment by jgosmann** [comment]
I think `normalize_encoders` should be added to the `Ensemble` constructor for consistency. If we are worried about the constructor becoming too long (it is becoming quite long), we should come up with some guide lines which things go in there and which do not.

**Comment by bmorcos** [comment]
Quick Vote for where to put `normalize_encoders`?

:+1: = put this in `__init__`
:-1: = leave this as a property of the ensemble only

**Comment by bmorcos** [comment]
The people have spoken! (all three of you!)

LGTM

**Comment by jgosmann** [comment]
I added a commit changing the position of the argument, see the commit message (314171f) for more details. LGTM :cake:

**Pull request merged**
