### PR TITLE
Improve Travis CI

### PR DESCRIPTION
**Pull request by Seanny123**
**Motivation and context:**
We could make Travis CI run faster and more reliably if we use caching, as discussed in #1217. Also, reduced the amount of Nengo history we were cloning from Git and make sure pip was installing in the user space.

**How has this been tested?**
Tested by trying to get the tests to pass on Travis

**How long should this take to review?**
- Quick (less than 40 lines changed or changes are straightforward)

**Where should a reviewer start?**
Start by reading the links associated the issue.

**Types of changes:**
- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**
- [x] I have read the **CONTRIBUTING.rst** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Seanny123** [comment]
At this point, `conda` is failing to install `numpy` as a module for reasons I don't understand. I'm going to sleep on it and revisit this later. Alternatively, @tbekolay if you have any ideas, let me know.

**Comment by tbekolay** [comment]
I pushed a squash commit putting it back into one file. I'm also not convinced we need the `CACHE_NAME` variables since we have other environment variables that should disambiguate the jobs (if I'm reading [this](https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices) correctly).

> conda is failing to install numpy

This happened because we use a conda environment (called test). It was being activated (`source activate test`) in the `install-conda.sh` script, not in `.travis.yml`. That would be fine if we sourced `install-conda.sh`, but we were executing it, which makes a subshell rather than executing it in the current shell.

Putting it back into one file has the nice side-effect of fixing that since we're not calling another script ;)

**Comment by Seanny123** [comment]
I bow down to your awesome Travis and Conda skills.

**Comment by Seanny123** [comment]
This LGTM. I don't know who technically "owns" this pull request, but I'm going to go ahead and say it needs review by one more person.

**Comment by tbekolay** [comment]
So one thing that's a bit concerning to me is that the jobs aren't actually running faster at all; I've restarted them a few times and it seems like the cost to load things up from the cache is about the same as installing Miniconda. Without the speedup, I feel like we're opting for one suboptimal process over another; I don't mind restarting builds that fail for Conda reasons, but we could get into really weird situations with a cache where we use the wrong versions of things, which will be annoying to debug. What do you think @Seanny123?

**Comment by Seanny123** [comment]
> we could get into really weird situations with a cache where we use the wrong versions of things, which will be annoying to debug

Actually, that's a good point. Does this script capture the case that a new version of packages are released?

**Comment by tbekolay** [comment]
> Does this script capture the case that a new version of packages are released?

It does not right now; it could be made to do so by doing the `conda update --all` whether the conda is cached or not (TravisCI will re-cache any changes to cached files).

I think I'm still :-1: on using the cache as switching to it will mean that your install process isn't tested.

**Comment by Seanny123** [comment]
> using the cache as switching to it will mean that our install process isn't tested

One possible solution to that is have a Travis CI environment that just tests the build process, but then I guess that only reduces the probability of the `conda` download failing, which doesn't seem ideal. In which case I think I'll close this pull request (without deleting the branch) and investigate making our own private mirror of `conda` using something as simple as a `cron` job and an sftp server.

**Pull request closed without merging**
