### PR TITLE
Add SimVoja operator using add_op.

### PR DESCRIPTION
**Pull request by e2crawfo**
Need this change because nengo_mpi overrides add_op.

### CODE REVIEW

**Comment by Seanny123** [comment]
LGTM. Is there some way we can make sure this mistake won't happen again?

**Comment by e2crawfo** [comment]
We could rename it to _operators to discourage direct manipulation, and then make a property called operators which returns a copy of _operators. Not sure how people feel about that.

Also, can I merge as soon as its been reviewed? Been a while since I've done this :8ball:

**Comment by tbekolay** [comment]
> Also, can I merge as soon as its been reviewed? Been a while since I've done this

Me or @hunse will merge; I'm pretty free ATM so I'll merge shortly.

**Comment by tbekolay** [comment]
And I like the `_operators` change! Maybe in a separate PR though.

**Comment by hunse** [comment]
The `operators` property would have to return the list of operators as a tuple, so that people couldn't append to it. This would mean a bit more copying of stuff. Of course, people can always access `_operators` directly if they really need speed and know what they're doing. [This post](http://stackoverflow.com/questions/23474648/python-read-only-lists-using-the-property-decorator) talks a bit more about it, and the top answer says that copying a list to a tuple *often* has negligible overhead, whatever that means.

**Pull request merged**
