### PR TITLE
Added preservation/warranty notices to license

### PR DESCRIPTION
**Pull request by drasmuss**
Just took language from the MIT license to flesh out our LICENSE.rst a bit (it's basically an MIT license with a special exemption for commercial use now).

Also changed CONTRIBUTORS.rst to point to nengo.github.io/people.rst, so that it's clear where people should sign the CAA.

**How has this been tested?**

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**

- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [n/a] I have updated the documentation accordingly.
- [n/a] I have included a changelog entry.
- [n/a] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jgosmann** [comment]
@tbekolay One of the AppVeyor tests failed without apparent reason (hang when solving for package specification and timed out). It's not the first time I see this (though the other cases might have been in Nengo SPA). I suppose you don't have an idea how to fix this either? (There also seems to be no way to rerun the test like in Travis-CI.)

**Comment by drasmuss** [comment]
I've noticed the same thing on a different project, so I think it's just an appveyor issue, or maybe appveyor+conda?

**Comment by tbekolay** [comment]
> (There also seems to be no way to rerun the test like in Travis-CI.)

When I'm logged in, I see a "Re-build commit" button at the top right (where "Cancel build" would be if the build was running). Does that not show up when you're logged in for SPA builds?

**Comment by jgosmann** [comment]
> Does that not show up when you're logged in for SPA builds?

Actually it does (for nengo_spa builds, not nengo builds). It just didn't occur to me that I have to log in (for Travis-CI I stay logged it, but this doesn't seem to be the case for AppVeyor).

**Pull request merged**
