### PR TITLE
Linearfilter combine

### PR DESCRIPTION
**Pull request by hunse**
**Motivation and context:**

It can be helpful to combine two LinearFilters, for example to see what the effects of passing through two subsequent synapses would be.

**How has this been tested?**

Added a little unit test.

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**

- New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by arvoelke** [comment]
FYI if you want to try this out in another way for point of comparison, you can currently do this using the multiplication operator in `nengolib`, i.e.,

```
from nengolib import Lowpass
nengo.Connection(pre, post, ..., synapse=Lowpass(0.1)*Lowpass(0.2))
```

which is also equivalent to using `DoubleExp(0.1, 0.2)`. This can be done in all versions of `nengo>=2.1.0`.

**Comment by Seanny123** [comment]
Any particular reason why this should be in Nengo core vs. extras?

**Comment by hunse** [comment]
It adds to a class that's in Nengo. I'm not exactly sure how it would work
in nengo_extras.

**Comment by hunse** [comment]
Added a changelog entry.

**Pull request merged**
