### PR TITLE
allows empty rasters

### PR DESCRIPTION
**Pull request by celiasmith**
this is useful for generating animations

### CODE REVIEW

**Comment by tbekolay** [comment]
This looks great! I'm curious if we shouldn't bother with `eventplot`? My reasoning here is that running `test_rasterplot` generates a 15KB PDF without eventplot, and 3.1MB with eventplot. My understanding of why this happens is because `plot` uses [BLITting](https://en.wikipedia.org/wiki/Bit_blit), while `eventplot` does not.

Alternatively, we could use `eventplot` but rasterize it, which reduces the PDF size to 84KB, but (since it's rasterized) doesn't look as nice as the `plot` version when you zoom in closely.

**Comment by hunse** [comment]
The difficulty with plot is choosing a good marker size. This isn't too big of a problem if you know your figure size and number of neurons in advance (such as when making figures for a paper), since you can just play around with the marker size until it looks good. The problem occurs when you want to be able to resize the figure, since there's no way to tie the marker size to the axes (data), so for example if you make the figure larger then the markers will be too small by comparison.

But I didn't realize that the difference in file sizes was so large, and taking out eventplot would make the code easier. Another option is to turn eventplot off by default, but still have it there if people really want it.

**Comment by tbekolay** [comment]
I like the idea of plot by default, and eventplot still available if desired. I'll try implementing a heuristic marker size based on the figure size and the number of neurons at the point when `rasterplot` is called, but yeah, if people change the figure size after the fact we can't do much (though, it is possible to implement a figure resize handler, it'd just be Matplotlib backend-specific).

**Comment by hunse** [comment]
I added a heuristic for the marker size that seems to work pretty well.

**Comment by tbekolay** [comment]
Great! Let me test it out a bit then I'll merge.

**Comment by tbekolay** [comment]
Added some commits; take a look @hunse and if it looks good I'll merge.

**Comment by hunse** [comment]
LGTM, but this is getting tripped up on the Mock plot objects used to skip plotting in the examples.

**Comment by tbekolay** [comment]
Oh right! Forgot about that. Will fix tomorrow.

**Comment by tbekolay** [comment]
Hacked together a fix in c9ae1ef. Look good @hunse or too much of a hack?

**Comment by hunse** [comment]
I was trying to think if there's a decent comment you could put there to explain it, but I can't think of anything.

I think that hack will be fine for the time being. It would be nicer if we could somehow completely skip things like `rasterplot` when we're using the mock plotter, but I don't know an easy way to do that, so we can just patch these kinds of problems as they crop up.

**Pull request merged**
