### PR TITLE
Added matrix multiplication network. Removed matrix mult test from test_...

### PR DESCRIPTION
**Pull request by youzak**
...ensemblearray. Fixed the matrix mult notebook example.

### CODE REVIEW

**Comment by jgosmann** [comment]
I rebased this and brought the code up to date with current best practices. This still needs some documentation.

**Comment by drasmuss** [comment]
I think given our loose plan to start moving pre-built networks into their own repositories, this might fit best as a `nengo_extras` thing for now. Thoughts on moving it over there?

**Comment by jgosmann** [comment]
I would be fine with that. But we should discuss in general the criteria for inclusion in packages which is sort of happening in #1144.

**Comment by jgosmann** [comment]
This should be ready for review now. Because I did a major overhaul of the network two other people than me should review this.

There is still the open question of which networks should be shipped with core Nengo. I can move this PR over to `nengo_extras` if desired.

**Comment by jgosmann** [comment]
Superseded by nengo/nengo_extras#24.

**Pull request closed without merging**
