### PR TITLE
Factored out `sample` function

### PR DESCRIPTION
**Pull request by tbekolay**
**Motivation and context:**
The ensemble tuning function in #871 needed access to the builder's `sample` function. We're moving #871 to `nengo_extras`, but it's a good idea to move the `sample` function anyhow, as it's used in several places.

Originally @drasmuss moved this to `nengo.utils.builder`; I figured it's not bad to have in `nengo.dists`. Though, since it's not quite the same as `Distribution.sample` we should perhaps rename it to something? `sample_if_needed` or something?

**Interactions with other PRs:**
Supercedes #871.

**How has this been tested?**
Ran the test suite locally. Doesn't require additional testing.

**How long should this take to review?**
- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**
- New feature (non-breaking change which adds functionality)

**Checklist:**
- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- [NA] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Still to do:**
- [x] We should decide if we're okay with having this in `nengo.dists`, and whether we should keep it named `sample` or something more explicit.
- [x] Changelog entry (once we decide the point above) since it maybe become part of the frontend API.

### CODE REVIEW

**Comment by jgosmann** [comment]
How about `get_samples`? That name would agnostic to whether the samples are obtained by sampling or just returning existing samples.

**Comment by tbekolay** [comment]
> How about `get_samples`?

Yeah, I can see that! What do you think about renaming the first argument to `dist_or_samples`? Seems to cover all the bases

**Comment by jgosmann** [comment]
> What do you think about renaming the first argument to dist_or_samples?

I'm fine with that; I'm also fine with `dist`.

**Comment by drasmuss** [comment]
Renaming and relocation both sound fine to me.

**Comment by jgosmann** [comment]
LGTM :cake:

**Comment by Seanny123** [comment]
LGTM.

**Comment by tbekolay** [comment]
In order to check all the boxes above, I added a docstring, then realized we don't have the distributions anywhere in the docs. So I added them (and fixed up our current docstrings to print nicely) in ef5d221cced139790bec and added the docstring and a changelog entry. I think those don't warrant two re-reviews, so @jgosmann can you take a look at this and merge if they look good to you?

**Pull request merged**
