### PR TITLE
Spa bg params

### PR DESCRIPTION
**Pull request by xchoo**

### CODE REVIEW

**Comment by xchoo** [comment]
Note: Travis-CI is failing because of #809. Actual tests are not failing. :smile:

**Comment by Seanny123** [comment]
#809 was fixed, but this is still breaking with a weirder error that has something to do with miniconda not doing a great job at installing stuff. @tbekolay sorry to ping you again, but have you already seen this error? I seem to remember you mentioning about opening a bug with miniconda?

**Comment by hunse** [comment]
This looks all right to me.

**Comment by tbekolay** [comment]
Needs a changelog entry I think.

**Comment by xchoo** [comment]
@tcstewar Would be the best person to do that. He added some stuff in this PR that I don't use.

**Comment by jgosmann** [comment]
This PR is quite old, marked as needs changes, and misses a description what it does ... :cry: 
So ...
* Is this PR still relevant? (If so, why was there no interest to get this merged sooner?)
* Can someone give me an explanation what this PR does?
* Can someone tell me what changes are required?

Basically, I would like to figure out if I should bring this up-to-date and merge into new-spa or whether I can close it.

**Comment by tcstewar** [comment]
Ah, this PR was a result of wanting to split the GPi and SNr inside the basal ganglia into two separate parts.  The reason to do this was to model Parkinson's (which only affects one, not the other).

As to what we want to do with it....  hmm.  I'd say not to do it.  Instead, this should be a separate basal ganglia available elsewhere (perhaps in nengo_extras), as an example of how people can implement things differently and still use them within a larger spa context.

**Comment by jgosmann** [comment]
ok, I'll then close this as revise and resubmit.

**Comment by tbekolay** [comment]
Note that this is used in a published paper, so it definitely needs to be available somewhere. Please no one delete the branch!

**Comment by jgosmann** [comment]
Would it make sense to create a tag for this branch? To me it seems that a tag is less likely to be accidentally removed ...

**Comment by tbekolay** [comment]
That would make sense! [Tag made](https://github.com/nengo/nengo/releases/tag/spa_bg_params), branch deleted, thanks @jgosmann :)

**Pull request closed without merging**
