### PR TITLE
Fixes for 2.2.0 release

### PR DESCRIPTION
**Pull request by tbekolay**
**Motivation and context:**
Was following our steps for releasing, and got some test failures for slow tests. Turns out our assumption that some of the SPA code was there just to support JavaViz was incorrect (see #1005, #1165) and caused the SPA examples to fail.

Since I was had to make that change for 2.2.0 anyway, I also did a bunch of other minor fixes that I've been queueing up for the next release... none of them are mission critical so not worth making a PR or changelog entry for, but hey, still worth doing. See b985ecc85565d75d585b4 for those details (happy to split those into separate commits if people think it'd be better that way).

**How has this been tested?**
Generated the documentation and ran all the slow tests.

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**

- Bug fix (non-breaking change which fixes an issue)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [NA] I have updated the documentation accordingly.
- [NA] I have included a changelog entry.
- [NA] I have added tests to cover my changes. 
- [x] All new and existing tests passed.

**Notes:**

Once this is reviewed and merged, I'll cut the 2.2.0 release.

(sidenote: how do people feel about putting NA in there for not applicable? I could add it to the PR template in this PR if it feels good)

### CODE REVIEW

**Comment by jgosmann** [comment]
b985ecc LGTM
I'm unsure about e7b0edc. If we made the `vocab` argument of the `SPA.similarity` method mandatory, it wouldn't be necessary. (I actually always used `spa.utils.similarity`, so I never ran into this.)

> (sidenote: how do people feel about putting NA in there for not applicable? I could add it to the PR template in this PR if it feels good)

It breaks the markdown rendering somewhat. :/

**Comment by tbekolay** [comment]
> If we made the vocab argument of the SPA.similarity method mandatory, it wouldn't be necessary.

Could be, we'd have to edit the SPA examples then, and yeah, I was hoping that we could just leave all that kind of stuff for after the split. Do you think it would be quick and easy? If so that's probably fine, but yeah, it feels like we wouldn't want to make API changes to SPA right now.

> It breaks the markdown rendering somewhat. :/

Yeah, that's kind of the point since in the [PR list](https://github.com/nengo/nengo/pulls) it lists how many boxes are checked and unchecked. By putting NA in there it removes it from that count... right now, I think we mostly ignore these checkboxes because it's valid for some of them to be unchecked sometimes. This way we are explicit that this checkbox shouldn't be checked (because it's not applicable in this PR). Not saying it's a perfect solution, but there have been a bunch of times that we haven't added changelog entries because we're mostly glossing over this list. Happy to hear other proposals, but also we should probably move that to a separate issue / PR!

**Comment by jgosmann** [comment]
> Do you think it would be quick and easy?

Yes, it is quick and easy.

> If so that's probably fine, but yeah, it feels like we wouldn't want to make API changes to SPA right now.

That's why I'm unsure about it.

**Comment by jgosmann** [comment]
Given the discussion from the dev meeting today, I'm fine with both commits.

**Comment by hunse** [comment]
LGTM. No point in trying to fine-tune SPA stuff while it's still part of this repo, IMO, so just reverting back to the working behaviour makes sense to me.

**Comment by tbekolay** [comment]
Cool cool, I'll do the release once someone merges (@hunse, mind doing the honors?)

**Pull request merged**
