### PR TITLE
Modifying semantic pointers in a vocabulary.

### PR DESCRIPTION
**Pull request by pblouw**
Currently, vocabularies store info about SPs in two separate places: the `.pointers` dictionary that maps vocabulary keys to SemanticPointer objects, and the `.vectors` array whose rows correspond to the vector attributes of each SP in the vocabulary.  It is possible to modify an SP in one of these places and not the other, which can lead to confusing errors of the sort reported in nengo/nengo_gui#438. (e.g. one might want to change the SP associated with a particular key to be structured in some way, randomly perturbed, or whatever). So, this PR introduces a `set_value` method that takes a key and vector as input and updates the vocabulary such that `.pointers` and `.vectors` are consistent with one another. 

I've flagged this pull request as a discussion, since it is not obvious to me that this is the best solution to this problem. Another option would be to get rid of the pointers dictionary altogether and create new SemanticPointer objects each time `__getitem__` is called by indexing into the `.vectors` array.

### CODE REVIEW

**Comment by Seanny123** [comment]
SPA is in a bit of a state of tumultuous change, so it is my opinion that this should be revisited after #1014 is merged. Actually, is it possible that the functionality of the new `VocabularySet` mapping satisfies your requirements?

**Comment by pblouw** [comment]
Sure, I'm fine with revisiting this later. Though I'm not sure that the new `VocabularyMap` will solve the problem, since as far I can tell vocab objects will still retain info about each SP in both `.vectors` and `.pointers`, and it's still easy to modify one without modifying the other.

**Comment by jgosmann** [comment]
Yes, this issue won't be solved by #1014 and related PRs.

**Comment by jgosmann** [comment]
Semantic pointers and the `Vocabulary.vectors` matrix will be readonly in new-spa to prevent accidental modification. If there is a valid use case, we could add a method to `Vocabulary` to change an item in the vocabulary, but I would prefer not to.

**Pull request closed without merging**
