### PR TITLE
More descriptive step function names

### PR DESCRIPTION
**Pull request by hunse**
Step function names are now specific to operators. This can help
with debugging.

### CODE REVIEW

**Comment by Seanny123** [comment]
LGTM

**Comment by arvoelke** [comment]
Nit: `examples/usage/rectified_linear.ipynb` still has a `step()` function.

LGTM

**Comment by hunse** [comment]
@arvoelke : feel free to change it if you want. The main benefit I would see is that it would suggest to users that they should give their step functions descriptive names for debugging.

**Comment by arvoelke** [comment]
Done :beers:

**Comment by tbekolay** [comment]
This is pretty minor, and so fine, but I'd still prefer that the person making the PR not be the one that merges it.

**Comment by hunse** [comment]
I know, but it was pretty minor...

**Comment by hunse** [comment]
We need more people who can/will merge stuff...

**Comment by tbekolay** [comment]
I know, it was minor. It would be good to have more people that are comfortable with git, but it's a hard thing to learn...

**Comment by Seanny123** [comment]
I thought the problem with merging was that there are few people (Dan, Jan,
you and Eric) who understand the code base well enough to merge with
confidence?

**Comment by tbekolay** [comment]
That too!

**Comment by drasmuss** [comment]
I'll try to be more active with merging, I've been slacking off.

**Pull request merged**
