### PR TITLE
Build synapses

### PR DESCRIPTION
**Pull request by hunse**
Remove `filtered_signal` from the builder, and just build synapses directly.

### CODE REVIEW

**Comment by tbekolay** [comment]
Pushed a small fixup commit to avoid using the builtin variable name `input` (used `input_sig`).

I was initially a bit concerned that the synapse builder doesn't store the signal anywhere, but I think this approach is better because it allows the builder that's calling this builder to store the signal somewhere instead (synapses don't exist outside of other objects, after all).

So yeah, I'll merge if @hunse is ok with the variable name change!

**Comment by hunse** [comment]
Personally, using `input` as a variable name doesn't bother me. No one should be using the `input` function anyway, and there's precedent in other packages, like this [code I copied from Scipy](https://github.com/nengo/nengo/blob/master/nengo/utils/filter_design.py#L288).

But if you want to change it, that's fine. I'll also change it above. Also, `input_sig` is not a keyword arg, so we probably should just use it positionally, which means the name is much less of an issue. I'll add that change.

**Comment by hunse** [comment]
Okay, added a fixup.

**Comment by tcstewar** [comment]
> Personally, using input as a variable name doesn't bother me.

As a tangential note, I've stopped using ```input``` as a variable name in all tutorials and nengo/nengo_gui example code, just because the syntax highlighters in most editors pick up on it and so it looks weird.  Much less of an issue in core code like this, but I thought I'd mention why I'm doing it elsewhere...  :)

**Comment by tbekolay** [comment]
> syntax highlighters in most editors pick up on it

That's why I changed it too :) I think it's less of an issue here since it's an arg to a function, but yeah, doesn't hurt to change it I think. And using it positionally is good too. Merging!

**Pull request merged**
