### PR TITLE
marker size change

### PR DESCRIPTION
**Pull request by celiasmith**
**Description:**
Changes the size of markers on the spike rasters when plotting with rasterplot

**Motivation and context:**
Rasters are usually plotted without overlap of spikes from different neurons, this makes that the case for Nengo.

**How has this been tested?**
Ran raster plots for papers across a few models.  Only on Mac OSX.

**Where should a reviewer start?**
It's one line.  I'd start there. 🍶 

**How long should this take to review?**
10 seconds

**Types of changes:**
?
- New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [ ] I have included a changelog entry.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tbekolay** [comment]
I remember spending a long time picking that constant... the issue that I found was that any value that worked well for a certain number of neurons worked poorly for a different number of neurons. I sort of got around it by scaling by axis height, but that was a bit of a hack; in actuality, it should probably scale by some combination of axis height and the number of neurons... I believe the marker size is in units of points squared, so there's probably a square root in there too? I'll look into this more.

**Comment by celiasmith** [comment]
I checked this value for numbers of neurons from 2-100 and it seemed ok... i think that's a good 'reasonable' range.  The previous value didn't look ok at all for small numbers of neurons.

**Comment by drasmuss** [comment]
Updated constant looks slightly better to me, here's an image for comparison (updated constant is bottom row):
comparison
You'll still get overlap for different sized plots, but at least this looks ok for the default plot size, and I'm not super motivated to do some fancy scaling to get it to work in all cases.

I also added a small fixup commit to update the documentation in that rasterplot function, which was wildly out of date.  I squashed it in already (assuming it would be uncontroversial), as I was already fiddling with the history to update @celiasmith commit message to conform to our [guidelines](https://pythonhosted.org/nengo/contributing.html#commit-messages) :wink:.  And rebased to master while I was at it.

**Comment by celiasmith** [comment]
man, that @celiasmith guy didn't even follow the guildines! what a douche.  he was probably overwhelmed with the complexity of his added code.

**Comment by tbekolay** [comment]
New plots LGTM; I pushed a fixup to add a changelog entry and fix up the example formatting a bit (interpreter sessions have a different starting marker for prompts versus continuations of a previous prompt). If it looks good to you @drasmuss fix it up and merge :+1: :rainbow:

**Pull request merged**
