### PR TITLE
Added citation for ALIF neurons

### PR DESCRIPTION
**Pull request by hunse**
Someone asked @arvoelke for this, so I figured I'd add it here so it's readily available.

### CODE REVIEW

**Comment by arvoelke** [comment]
Great, thanks! (Also LGTM)

**Comment by Seanny123** [comment]
@tbekolay TravisCI seems to be barfing again.

**Comment by tbekolay** [comment]
Travis :(

**Comment by jgosmann** [comment]
@Seanny123 It says all checks have passed?

**Comment by tbekolay** [comment]
I restarted the builds; there was something weird going on with miniconda, it was borking on `source activate test`. Not sure if it was a conda or TravisCI issue, but it fixed itself!

**Pull request merged**
