### PR TITLE
Simplified signal logic again

### PR DESCRIPTION
**Pull request by hunse**
This is a new version of #681. I took @drasmuss's commit to remove the SignalView stuff and just use Numpy for all our slicing needs, and modified it a bit. I also took out the controversial stuff about moving the simulation values from the simulator's SignalDict to the signals themselves. We can always do that later if we want, since it's not directly related to these changes.

### CODE REVIEW

**Comment by tbekolay** [comment]
I'm curious to do a bit of speed / memory profiling of this PR, but looking through the code I'm quite happy with how much it's simplified things!

**Comment by hunse** [comment]
The code I used for memory profiling is in the `memory-use2` branch. It's a bit messy since I just kept tacking stuff on to get more detail into certain parts, but it works pretty well (it helped me find some of those needless copies, anyway).

**Comment by hunse** [comment]
Okay, got this working with Numpy 1.6, so I think it's all good now (fingers crossed).

**Comment by hunse** [comment]
I think it would be good to get this in 2.1 if it's not too much work. It makes things a lot cleaner and it will help me in Nengo OCL too.

**Comment by tbekolay** [comment]
I'll take a look today!

**Comment by hunse** [comment]
Thanks! I just rebased it.

**Comment by hunse** [comment]
I fixed up `LICENCE.rst`.

**Comment by tbekolay** [comment]
Awesome, this looks great to me. @drasmuss, since you started off this process, could you give this a review as well?

**Comment by drasmuss** [comment]
I might be inclined to rename `signal.value` to `signal.init_value`, just to be clear what its role is.  That's a minor nit though, other than that looks good to me.

**Comment by tbekolay** [comment]
> rename signal.value to signal.init_value

That is definitely more clear! I was a bit worried because I thought that we used `.value` a lot in the code, but actually we only use it in about 10 or so lines (if my `grep`ping is right). So my vote would be for `init_value` or `init_val` or `initial_val` or something like that too.

**Comment by hunse** [comment]
Okay, I renamed it to `initial_value`, i.e. none of the things you suggested!

**Comment by drasmuss** [comment]
Looks good to me.

**Comment by tbekolay** [comment]
I totally implied `initial_value` though! It was there in spirit.

I'll clean up the history and merge!

**Pull request merged**
