### PR TITLE
Fix arg repr in Learning Rules

### LINKED ISSUE #1219: Voja learning rule missing _argreprs
Noticed while working on #387

https://github.com/nengo/nengo/blob/master/nengo/learning_rules.py#L274

### PR DESCRIPTION
**Pull request by Seanny123**
**Motivation and context:**
Resolves #1219. 

**How has this been tested?**
Run the following code:
```
import nengo

vj = nengo.Voja(post_tau=0.1, learning_rate=0.1)
print(vj) #should show arguments
noarg_vj = nengo.Voja()
print(noarg_vj) # should not show arguments
```

**How long should this take to review?**
- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**
- New feature (non-breaking change which adds functionality)

**Checklist:**
- [x] I have read the **CONTRIBUTING.rst** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bmorcos** [comment]
This isn't specific to Voja, but do we want to change the `%f` format as it returns trailing zeros? here `post_tau` uses `%f` and `learning_rate` uses `%g`
```
In [2]: vj = nengo.Voja(post_tau=0.5, learning_rate=0.5) 
In [3]: print(vj)
Voja(post_tau=0.500000, learning_rate=0.5)
In [4]: vj = nengo.Voja(post_tau=0.555555, learning_rate=0.555555) 
In [5]: print(vj)
Voja(post_tau=0.555555, learning_rate=0.555555)
```

**Comment by tcstewar** [comment]
> This isn't specific to Voja, but do we want to change the %f format as it returns trailing zeros? here post_tau uses %f and learning_rate uses %g

Good catch...  yeah, ```%g``` is pretty much always preferred....

**Comment by bmorcos** [comment]
Should we just lump that in here? I can also do it while I work on #387

**Comment by Seanny123** [comment]
I made a quick fixup commit for the code I changed. For the rest of them, I would put it into a separate PR. PRs should generally only accomplish one objective.

**Comment by tbekolay** [comment]
> For the rest of them, I would put it into a separate PR. PRs should generally only accomplish one objective.

In principle I totally agree, but in this case I wouldn't want to go through the hassle of making a whole new PR that has to be reviewed twice for changing a 5 characters or so. I think it's fine for the objective of this PR to be "fixing up learning rule `_argreprs`"

**Comment by Seanny123** [comment]
Changed the rest of the representation strings and rebased. This PR is ready for it's final review.

**Comment by tbekolay** [comment]
Looking good to me! Added a fixup to include `Voja` in the `string.ipynb` notebook. Will merge once CI is done running unless someone stops me!

**Pull request merged**
