### PR TITLE
Add HebbError learning rule

### PR DESCRIPTION
**Pull request by hunse**
**Motivation and context:**

This is a very common type of learning in machine learning. I'm not sure if ``HebbError`` is a good name for it, and perhaps it has it's own name, but I've heard it described as a Hebbian rule on an error (i.e. weight updates are proportional to pre activities times the error in post activity space).

The PES rule is a type of this rule, where the error is the post error in vector space times the post encoders.

**How has this been tested?**

The unit test tests backprop-style learning on encoders in a network with fixed decoders. i.e. the decoders are generated randomly, and then the transpose of the decoders is used to propagate the output error back to adjust the encoders.

**How long should this take to review?**

- Average (neither quick nor lengthy)

**Types of changes:**

- New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [ ] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Still to do:**

- [x] Test this and add some unit tests
- [ ] Maybe add a notebook demonstrating it

### CODE REVIEW

**Comment by hunse** [comment]
I just put this here because I was playing around with it. It hasn't really been tested yet.

The learning rule equation is: 
image

I'm curious what people think: Is this a useful type of learning rule to have?

Also, I think all of our learning rules should have their update equation in their docstring.

**Comment by drasmuss** [comment]
Maybe just `DeltaRule` as a name?  That's basically what this is, with the assumption of a linear activation function (so no derivative term).

**Comment by hunse** [comment]
I think `DeltaRule` is a good name. I've made the change.

I think this is ready for review. It still needs changelog entries, which I can do.

I added a commit at the end that allows LinearFilters to be combined. Maybe this should be part of a different PR, I just thought of it while I was doing this one and it's a pretty small addition.

**Comment by jgosmann** [comment]
I took a look at this, but I have a hard time understanding the intuition behind this learning rule.

* What exactly is meant by `e_i is the input error in the postsynaptic neuron space`? Is this saying how much higher the postsynaptic neuron activity should be?
* So if the activity of a postsynaptic neuron is too low, the connection weights from presynaptic neurons get increased to increase the postsynaptic activity?
* Can you add some explanation of what the network is supposed to do? Especially why `decoders` is generated in that particular way is not clear to me and why those are used in the places they are used. What is the purpose of `y`?
* In more general terms it would be nice to have a notebook demonstrating the learning rule and giving and intuition in what sort of situations it can be used.

Somewhat aside: Do we have a policy on the inclusion of learning rules in core Nengo? It seems that there could be a vast number of learning rules that we could possibly include ...

**Comment by hunse** [comment]
Moved to nengo/nengo_extras#42

**Pull request closed without merging**
