### PR TITLE
Declare entry point for nengo reference simulator.

### PR DESCRIPTION
**Pull request by jgosmann**
**Description:**
This adds an entry point for the reference simulator so that other Python packages (like nengo_gui) can discover the backend in a general way. Such an entry point should become best practice for all backends.

**Motivation and context:**
See description.

**How has this been tested?**
1. Checkout the branch and do a `python setup.py develop`.
2. Run the following Python code:

```python
from pkg_resources import iter_entry_points
print([ep.load() for ep in iter_entry_points(group='nengo.backends')])
```
It will print "[<class 'nengo.simulator.Simulator'>]".

**Where should a reviewer start?**
Click "Files changed".

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**

- New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [ ] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Still to do:**

- Add some documentation, but we need some general backend developer documentation first. I'll create an issue for that.

### CODE REVIEW

**Comment by tbekolay** [comment]
> It will print "[]".

I get `[<class 'nengo.simulator.Simulator'>]` which I'm pretty sure is actually what we want ;)

Aside from that, this looks good to me! I pushed a commit adding a test.

**Comment by jgosmann** [comment]
That's the markdown messing with me ... click the edit icon and you will see I put in in there. I'm innocent. I promise. 😇

**Comment by jgosmann** [comment]
It would also be possible to load a specific entry point without iterating over all. Might that be more appropriate for the test?

**Comment by tbekolay** [comment]
The advantage of loading them all (which shouldn't take long) is that we don't have to write a different test for each backend; also, failing this test will let backends know that they should also declare this entry point.

**Comment by jgosmann** [comment]
Good point!

**Comment by Seanny123** [comment]
Given that the only test that is not passing was fixed by #1134, this branch looks ready to merge.

**Pull request merged**
