### PR TITLE
Fix evaluation of IPyNBs for documentation.

### LINKED ISSUE #477: Low priority: docs won't build on Linux Mint 17
Here are the contents of the error log. I'm running Linux Mint 17 with iPython 2.2.0. With the exact same configuration, it runs on Ubuntu 14.04, so I really don't know what's going on here and it's not that important, but I thought I would note it down just in case it comes up again.

    # Sphinx version: 1.2.3
    # Python version: 2.7.6
    # Docutils version: 0.12 release
    # Jinja2 version: 2.7.2
    # Loaded extensions:
    #   sphinx.ext.autodoc from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/autodoc.pyc
    #   sphinx.ext.mathjax from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/mathjax.pyc
    #   numpydoc from /home/saubin/git/nengo-docs/src/numpydoc/numpydoc/__init__.py
    #   sphinx.ext.viewcode from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/viewcode.pyc
    #   nengo.utils.docutils from /home/saubin/git/nengo-docs/nengo/utils/docutils.pyc
    #   sphinx.ext.todo from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/todo.pyc
    #   sphinx.ext.autosummary from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/autosummary/__init__.pyc
    #   sphinx.ext.oldcmarkup from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/oldcmarkup.pyc
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/cmdline.py", line 254, in main
        app.build(force_all, filenames)
      File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/application.py", line 220, in build
        self.builder.build_update()
      File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/builders/__init__.py", line 214, in build_update
        'out of date' % len(to_build))
      File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/builders/__init__.py", line 234, in build
        purple, length):
      File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/builders/__init__.py", line 134, in status_iterator
        for item in iterable:
      File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/environment.py", line 478, in update_generator
        self.read_doc(docname, app=app)
      File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/environment.py", line 628, in read_doc
        pub.publish()
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/core.py", line 217, in publish
        self.settings)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/readers/__init__.py", line 72, in read
        self.parse()
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/readers/__init__.py", line 78, in parse
        self.parser.parse(self.input, document)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/__init__.py", line 172, in parse
        self.statemachine.run(inputlines, document, inliner=self.inliner)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 170, in run
        input_source=document['source'])
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2961, in text
        self.section(title.lstrip(), source, style, lineno + 1, messages)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 327, in section
        self.new_subsection(title, lineno, messages)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 395, in new_subsection
        node=section_node, match_titles=True)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 282, in nested_parse
        node=node, match_titles=match_titles)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 195, in run
        results = StateMachineWS.run(self, input_lines, input_offset)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2299, in explicit_markup
        nodelist, blank_finish = self.explicit_construct(match)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2311, in explicit_construct
        return method(self, expmatch)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2054, in directive
        directive_class, match, type_name, option_presets)
      File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2103, in run_directive
        result = directive_instance.run()
      File "/home/saubin/git/nengo-docs/nengo/utils/docutils.py", line 97, in run
        evaluated_html = ipext.export_html(nb_eval)
      File "/home/saubin/git/nengo-docs/nengo/utils/ipython.py", line 141, in export_html
        output, resources = exporter.from_notebook_node(nb)
      File "/usr/local/lib/python2.7/dist-packages/IPython/nbconvert/exporters/templateexporter.py", line 209, in from_notebook_node
        nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
      File "/usr/local/lib/python2.7/dist-packages/IPython/nbconvert/exporters/exporter.py", line 119, in from_notebook_node
        if 'language' in nb['metadata']:
    TypeError: string indices must be integers, not str

### PR DESCRIPTION
**Pull request by jgosmann**
Fixes #477.

### CODE REVIEW

**Comment by jgosmann** [comment]
Not sure whether this should be in the 2.0 release. If none of the examples threw an error (which should be the case in the release), building the docs would work without this fix.

**Comment by tbekolay** [comment]
Can't hurt! So with this, when a notebook raises an exception or fails for another reason, it'll now raise a warning and just not generate the evaluated version, correct? I wonder if we should just raise the exception? This was an issue in the 1.4 documentation; it would fail silently, and every now and then someone would email me saying that some page or another is blank, which was a pain. I'd rather TravisCI tell us when documentation is broken... though I suppose technically it will since it tests that notebooks run without exceptions?

**Comment by jgosmann** [comment]
The original problem was, that instead of raising an exception a string instead of the notebook was returned leading to an unhelpful exception (and giving the function different return types which IMO is bad practice in most cases).

Whether we want to warn or raise an exception is a different issue. The reason for going with a warning was that most of the documentation will be ok and can be of use. Especially when working on some new feature you might have broken examples (which you'll fix at a later point), but still want some easy to browse HTML documentation of stuff you already added. As you say the tests are already ensuring that the examples will run.

In addition to that I might favour a zero warnings policy for the documentation and maybe there is a way to indicate a failure if there are warnings?

**Comment by tbekolay** [comment]
> The reason for going with a warning was that most of the documentation will be ok and can be of use.

Makes sense to me!

> In addition to that I might favour a zero warnings policy for the documentation and maybe there is a way to indicate a failure if there are warnings?

I'm all for that. Probably that's something we can set up with `tox` and TravisCI.

----

Right now I'm in the process of cleaning up the `docs` branch's history for merge; I'll include this commit in that branch somewhere.

**Comment by tbekolay** [comment]
This is incorporated in #371 now.

**Pull request closed without merging**
