### PR TITLE
Test solver fingerprinting.

### PR DESCRIPTION
**Pull request by jgosmann**
Addresses #1044.

Note that this test will fail without PR #1046.

### CODE REVIEW

**Comment by hunse** [comment]
LGTM

**Comment by hunse** [comment]
The test is failing now, though. I'm going to rebase and see if that helps.

**Comment by hunse** [comment]
Which it should, because #1046 is now merged. duh

**Comment by tbekolay** [comment]
;) This LGTM too btw so if CI testing passes feel free to merge.

**Comment by hunse** [comment]
One question though: do we want to test this for other FrozenObjects too? I mean really, we'd need a more automated way of testing every parameter on every FrozenObject if we want to be robust. Might be something to consider down the road.

**Comment by tbekolay** [comment]
> do we want to test this for other FrozenObjects too?

Hmm... this could be doable with the registry in #1068, which would be an argument for that approach over #1066.

**Comment by jgosmann** [comment]
> do we want to test this for other FrozenObjects too?

I don't think, this issue is specific to frozen objects, but could occur with any object having parameters (or even some sort of descriptor). For parameters this is solved by either making the class a FrozenObject or copyable. For the general case the class has to correclty implement pickling. So we can't test this for every potential case anyways.

**Pull request merged**
