### PR TITLE
Example reorg

### PR DESCRIPTION
**Pull request by celiasmith**
This is just a re-organization of the examples directory.  I checked to make sure nothing was upgraded to the next version of ipython notebook (Jupyter), and unfortunately, unsupervised-learning was changed (I can't change it back)... so if someone could fix that, that'd be great.

### CODE REVIEW

**Comment by tbekolay** [comment]
Made a few changes; see the FIXUP and SQUASH commit messages for details. Also see https://github.com/nengo/nengo/tree/example_reorg/examples for how the examples folder will look on Github once this is merged.

Will squash / merge / etc when someone takes a look and gives a +1!

**Comment by hunse** [comment]
I moved the convolution notebook to where it's supposed to be, and fixed a couple minor things in the README.

The links in the docs still need to be changed to reflect the new notebook locations.

Also, @tbekolay, don't forget to flatten out the history when you merge (right now it's not linear).

**Comment by tbekolay** [comment]
Thanks @hunse! Forgot about the docs, will change those now.

**Comment by tbekolay** [comment]
Docs changed. Will give another once over and merge soon.

**Comment by tbekolay** [comment]
OK, fixed the history, and realized that examples weren't being tested anymore. Made a new commit to fix that. @hunse, mind giving it a quick once over? I'll fixup and merge on your +1.

**Comment by hunse** [comment]
Looks good. Good thing you remembered the tests!

**Comment by tbekolay** [comment]
Mostly just because the example testing stuff has come up recently ;) Lucky!

**Pull request merged**
