### PR TITLE
Missing spa examples

### PR DESCRIPTION
**Pull request by jgosmann**
Depends on PR #604 (branch `fix-spa-warnings`).

### CODE REVIEW

**Comment by hunse** [comment]
I took a look at these, and I think they need a bit of extra discussion, especially of the results. Right now, they're pretty much all code. I've started adding some discussion for `convolution.ipynb`.

**Comment by jgosmann** [comment]
Also added a few lines to the other two examples. Probably not perfect, but a start.

**Comment by tbekolay** [comment]
What's the status of this PR ATM? I think this and the docs is all that's left.

**Comment by hunse** [comment]
I think it's pretty much good to go. The only thing that's not done is adding labels to plot axes, but that's probably not essential.

**Comment by tbekolay** [comment]
Labels schmabels! I'll review / merge this.

**Comment by tbekolay** [comment]
Added a quick blurb to the start of `spa_parser.ipynb`, which was the only example without a lot of exposition, and added a bunch of these to the optional set of notebooks, as these take a while to simulate. Aside from that looks good; merging!

**Pull request merged**
