### PR TITLE
Small fixes to notebook examples

### PR DESCRIPTION
**Pull request by mgserafi**
**Motivation and context:**
Small fixes to plots and descriptions in example ipynb from #1247 and #1249 

**How has this been tested?**
Opened python notebooks and ensured equations match respective functions. Also checked that plot colours matched descriptions. I checked that the colours were consistent between matplotlib 1.5 and 2.0.

**How long should this take to review?**
- Quick (less than 40 lines changed or changes are straightforward)

**Where should a reviewer start?**
Open python notebooks and make sure description matches plot colours and connection functions.

**Types of changes:**
- Bug fix (non-breaking change which fixes an issue)

**Checklist:**
- [X] I have read the **CONTRIBUTING.rst** document.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jgosmann** [comment]
Can I ask you to run the `clearoutputs.py` script from the [ctn-waterloo/devscripts](https://github.com/ctn-waterloo/devscripts) repository on the changed notebooks? That should fix the failing unit tests and condense the diffs.

**Comment by tbekolay** [comment]
Alternatively you can open the notebooks in Jupyter and click on Cell > All Outputs > Clear.

**Comment by jgosmann** [comment]
Aren't we also doing a conversion of the notebook version in `clearoutputs.py`?

**Comment by mgserafi** [comment]
Previously I'd run 
```jupyter nbconvert mynotebook.ipynb --to notebook --nbformat 3 --output mynotebook.ipynb```
after editing the notebook. This time I ran `clearoutputs.py` but it looks like it got converted to version 4.

**Comment by mgserafi** [comment]
Just to clarify, we want to keep the notebooks in version 3, right?

**Comment by Seanny123** [comment]
LGTM.

**Pull request merged**
