### PR TITLE
Seed backends

### PR DESCRIPTION
**Pull request by hunse**
**Motivation and context:**

This makes seeding more accessible to backends. It separates out a seeding function for networks that backends can use. It respects existing values in the `model.seeds` and `model.seeded` dictionaries so that backends can set these for some (or all) objects and they won't be overwritten.

**Interactions with other PRs:**

This replaces #1476. 

**How has this been tested?**

There is a test making sure that values don't get overwritten. Otherwise, our current seeding tests cover this, and it's tested for backends in nengo/nengo-loihi#70.

**How long should this take to review?**

- Average (neither quick nor lengthy)

**Types of changes:**

- New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [ ] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] I have run the test suite locally and all tests passed.

### CODE REVIEW

**Comment by hunse** [comment]
So the static test here is failing because of an over-indented line in `params.py`. I'm confused, because a) my local flake8 doesn't catch this, and b) this line appears to have been like this since d2acfcd7. How is this just coming up now??

The other tests appear to just have errored mysteriously. They all pass locally for me, so I believe this is just a random thing.

**Comment by hunse** [comment]
When I upgrade my flake8 it catches this, so must've been a flake8 bug that it was missing it.

**Comment by tbekolay** [comment]
> The other tests appear to just have errored mysteriously. They all pass locally for me, so I believe this is just a random thing.

Definitely mysterious... but unfortunately I don't think it's random because [it's been happening for the past 2+ weeks](https://travis-ci.org/nengo/nengo/builds) and it [happens on Appveyor too](https://ci.appveyor.com/project/nengo/nengo/builds/22062967). I just pushed an empty commit to #1488 and you can see the [previously passing build](https://travis-ci.org/nengo/nengo/builds/454513077?utm_source=github_status&utm_medium=notification) versus the [currently erroring build](https://travis-ci.org/nengo/nengo/builds/488799842?utm_source=github_status&utm_medium=notification): previously speedy builds are now taking so long that they don't finish and end up timing out in the middle of running tests. I would think that this would indicate that something changed in the TravisCI images such that the way we're doing things is no longer performant, but since the same thing is happening on Appveyor that seems unlikely. The likely suspect is therefore Conda, but then we would have experienced a similar regression in terms of TravisCI build speed for Nengo Loihi, which I do not believe we experienced.

Looking through the logs in more detail, many of the logs seem to halt around the cache tests. I'm going to try skipping those tests to see if we can get through the test suite, as it could be a specific cache-related regression :man_shrugging:

**Comment by tbekolay** [comment]
Hm, so looking through the log [without cache tests](https://travis-ci.org/nengo/nengo/builds/488813762), it is getting farther, but I'm noticing that we are now running the tests marked `slow` even though we've asked for them not to be run, so now I'm thinking that the issue is actually due to newer versions of pytest affecting how we're marking and skipping slow tests. We were stalling out at the cache tests likely because the cache benchmarks take a long time to run in general, and I believe are some of the worst case scenarios for the virtual machines that TravisCI / Appveyor use, so this is starting to make more sense.

This might be fixed in #1497, so I will take a look at that PR now.

**Comment by hunse** [comment]
Fixups LGTM.

**Pull request merged**
