### PR TITLE
Add options to presets.ThresholdingEnsemble.

### PR DESCRIPTION
**Pull request by jgosmann**
**Description:**
Adds two more options to the thresholding preset to control the width of the intercepts and the radius of the thresholding ensembles.

**Motivation and context:**
Sometimes it can be useful to fine tune these parameters.

**Interactions with other PRs:**
none

**How has this been tested?**
The existing test for the preset still passes.

**Where should a reviewer start?**
The usual place.

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**

- New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Still to do:**

### CODE REVIEW

**Comment by Seanny123** [comment]
LGTM. I don't think this needs a changelog entry. I'm on the fence about whether we need a test to see if changing the radius actually works, but I'm leaning towards no, since it's really already covered by `ensemble` and `config` tests.

**Comment by jgosmann** [comment]
Actually, I should write a test and make sure that this works as intended. I just remembered that eval_points get scaled by the radius (intercepts maybe too?).

**Comment by jgosmann** [comment]
Regarding the changelog entry: I just added this PR to the existing entry. There wasn't a release wtih the preset yet.

**Comment by tbekolay** [comment]
Documenting presets is the last thing on my todo for 2.2.0, so this should be in before 2.2.0 too. Pushed a fixup to add the defaults to the docstring. LGTM! Will merge once tests finish.

**Pull request merged**
