### PR TITLE
Fix bad-mcs-classmethod-argument warnings.

### PR DESCRIPTION
**Pull request by jgosmann**
**Motivation and context:**
This is minor, but ensure consistent naming.

**Interactions with other PRs:**
Cherry picked from #1278 for easier review.

**How has this been tested?**
Added check to pylintrc, ran it, gave warnings, cherry picked the fix, ran pylint again, it succeeded.

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Where should a reviewer start?**

**Types of changes:**

- Bug fix (non-breaking change which fixes an issue)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [n/a] I have updated the documentation accordingly.
- [n/a] I have included a changelog entry.
- [n/a] I have added tests to cover my changes.
- [x] I have run the test suite locally and all tests passed.

### CODE REVIEW

**Comment by jgosmann** [comment]
The AppVeyor failure is unrelated.

**Comment by tbekolay** [comment]
Hm... I'm not sure about this one; apparently it conflicts with [PEP-8](https://github.com/PyCQA/pycodestyle/issues/503). I understand that metaclasses are quite different from normal classes, so it might be handy to differentiate them in some way, but I'm not convinced that `mcs` is a good name for it.

@jgosmann What do you think about setting `valid-metaclass-classmethod-first-arg` to `metacls`? Seems easier to understand at first glance, since most will be familiar with `cls` as the first arg to class methods.

**Comment by jgosmann** [comment]
I wasn't aware that PEP-8 contradicts pylint in this case. I'm fine with either leaving `bad-mcs-classmethod-argument` disabled or setting `valid-metaclass-classmethod-first-arg` to `metacls`.

**Comment by Seanny123** [comment]
Personally, I prefer setting valid-metaclass-arg

**Comment by tbekolay** [comment]
Sorry should have been explicit... PEP-8 would have us set `valid-metaclass-classmethod-first-arg` to `cls`, which frankly I'm also fine with. But if no one is strongly opposed, I'll set it to `metacls`.

**Pull request merged**
