### PR TITLE
Can read sliced signals from SignalDict

### LINKED ISSUE #967: Sliced voltage Probes don't work
This used to work but does not any more:

```python
import nengo

model = nengo.Network()
with model:
    ens = nengo.Ensemble(100, 1)
    p = nengo.Probe(ens.neurons[:2], 'voltage')
    
sim = nengo.Simulator(model)
with sim:
    sim.run(1)
```

This seems to be broken as of commit 82fa822 and means that Nengo GUI voltage probes do not work with the latest nengo.

### PR DESCRIPTION
**Pull request by hunse**
This allows things like slices on voltage probes to work.
Fixes #967.

### CODE REVIEW

**Comment by tcstewar** [comment]
Cool!  Thank you for the fast response on this!

Should a test case be added?  I'm not sure what the scope of the problem was....  :)

**Comment by hunse** [comment]
It was easy enough to modify a test to check the basic functionality of this. It doesn't test that all the slicing is correct for all different types and permutations of slices, but I don't think that's necessary.

**Comment by Seanny123** [comment]
FYI, the test is failing on Python 3 stuff.

**Comment by hunse** [comment]
Okay, this should fix Python3. I changed the Signal interface a bit to what I think is much clearer (it now has `strides` and `offset` both in bytes, and `elemstrides` and `elemoffset` in elements), but this will break any backends that use `offset`, because it's now in terms of bytes, not strides. @e2crawfo, do you use this on nengo_mpi? This is probably related to dealing with views in things like SlicedCopy, which I think you were working on recently, so maybe now is not a bad time to change this.

**Comment by e2crawfo** [comment]
Yeah, I'm in the process of improving how nengo_mpi deals with views, I'll make sure to use elemoffset instead of offset.

**Comment by hunse** [comment]
Great! This should be ready for re-review, then.

**Comment by drasmuss** [comment]
Looks good

**Comment by hunse** [comment]
@tbekolay can you merge? It will make some nengo_ocl stuff easier for me right now.

**Comment by tbekolay** [comment]
Sure, doing so now!

**Pull request merged**
