### PR TITLE
Matrix multiplication example fixes.

### PR DESCRIPTION
**Pull request by jgosmann**
**Motivation and context:**
I was starting to look at #431 and to understand how we do matrix multiplication in the first place I went through the example notebook and made a few changes (no need to merge all of them depending on what people think):
- There was one typo.
- It did not work with other matrix dimensions. Now it works with more (hopefully all).
- To me it seems clearer to use the product network instead of doing the product with an ensemble array.

**Interactions with other PRs:**
#431 also makes some changes, some of which address the same things. This PR supersedes the changes to the notebook in #431.

**How has this been tested?**
Executed the whole notebook with the matrices from the last commit. ~~Trying a few more matrix shapes wouldn't hurt, but I haven't done that yet.~~ Tried a bunch of other matrix shapes, all worked.

**How long should this take to review?**

- Average (neither quick nor lengthy)

**Types of changes:**

- Documentation

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jgosmann** [comment]
The test failure is unrelated to this ... I'll open an issue for that.

**Comment by Seanny123** [comment]
LGTM.

**Comment by Seanny123** [comment]
Do I need to review this again or did you just clean up the history?

**Comment by jgosmann** [comment]
Just rebased this and added a changelog entry. No need to review this again.

**Comment by tbekolay** [comment]
LGTM! Merging.

**Pull request merged**
