### PR TITLE
Insert spaces after # of markdown heading/comment.

### PR DESCRIPTION
**Pull request by jgosmann**
To have headings displayed correctly in Jupyter. Looked over all the examples and everything else seems to be rendered fine.
Addresses #806.

### CODE REVIEW

**Comment by Seanny123** [comment]
LGTM

**Comment by tbekolay** [comment]
LGTM too! One minor thing is that these changes should change the notebook's signature. But I think the signatures don't really matter at this point, you just get a minor warning in the console... this might change in the future though, but for now, I'll just merge.

**Comment by hunse** [comment]
> One minor thing is that these changes should change the notebook's signature.

It would be nice if there was some way to build it into our `clearoutputs.py` script, for example. There must be some IPython function somewhere for finding the hash.

**Comment by jgosmann** [comment]
After reading [the documentation on the notebook's signature](https://ipython.org/ipython-doc/dev/notebook/security.html#the-details-of-trust) I don't think that it matters in any way. The value depends on the profile and when loaded in any other profile the notebook will be untrusted anyways (and because the secret key is unknown in that other profile, there is no way to know whether the signature was the actual signature or not).

**Comment by hunse** [comment]
Oh yeah, I didn't realize there's a secret key in there too.

**Pull request merged**
