### PR TITLE
Moved gate, channel, convolution network to target module

### PR DESCRIPTION
**Pull request by s72sue**
Fix for #894

### CODE REVIEW

**Comment by s72sue** [comment]
Does anyone know what this error means?

**Comment by ikajic** [comment]
If you click on "Details" in box, you'll see a little red cross in a build job that failed. Now, you can click on that job and see that there's this line:
```
nengo/spa/thalamus.py:153:30: E128 continuation line under-indented for visual indent
```

so the error simply means that the code-style is not conforming to PEP standards and flake package checks for that. If you just indent ` synapse=self.synapse_to_gate, transform=-1)` in `thalamus.py` like it was before (so it is right below the bracket `(` in the line before), my guess is that this should pass.

**Comment by Seanny123** [comment]
After you fix the syntax error, this pull request looks good to me. Thanks for tackling the problem Su!

**Comment by s72sue** [comment]
Thanks Ivana and Sean!
@Seanny123 , You might want to take another look since I made some changes to the cortical. Since the conv network was moved to the target, it didn't make sense to keep the bias node in cortical, so I have moved that to the target (as required by #905). 

However, the cortical still shows up. Is that because nengo_gui creates a component for each spa module? If yes, should it be checking whether the module is empty?

**Comment by Seanny123** [comment]
Yeah, that's a bug for Nengo GUI to deal with.

**Comment by Seanny123** [comment]
@tbekolay are we still supposed to ping you for merges?

**Comment by tbekolay** [comment]
Eric and Dan can merge as well; anyone on the maintainers team. But yeah, I
can merge this tomorrow morning!

**Comment by tbekolay** [comment]
This makes some API changes, but they're unlikely affect many people, so I'm going to add a short changelog entry. Aside from that, looks great!

**Pull request merged**
