### PR TITLE
Changed defaults to match spaopt

### PR DESCRIPTION
**Pull request by tcstewar**
**Description:**
This PR changes the default radius of spa.State, spa.Bind, and spa.Compare modules to match the improved defaults from @jgosmann 's spaopt-v4 branch.  It also introduces the represent_identity option for spa.State objects in that branch. (however, it uses False as the default, rather than True)

**Motivation and context:**
This change to the defaults is independent of the more complex changes in spaopt-v4, and can be considered separately.  This change to the defaults is also fairly controversial, as it changes existing models.

**Interactions with other PRs:**
This PR takes the idea from #941 and reimplements just that one change.

**How has this been tested?**
I looked at the radii generated by three branches, as follows:

``` python
# branch master
import nengo
import nengo.spa as spa
model = spa.SPA()
with model:
    model.a = spa.State(6, subdimensions=2)
    model.b = spa.State(6, subdimensions=3)    
    model.c = spa.Compare(6)
    model.cc = spa.Bind(6)
print 'a.radius:', [ens.radius for ens in model.a.all_ensembles]
print 'b.radius:', [ens.radius for ens in model.b.all_ensembles]
print 'c.radius:', [ens.radius for ens in model.c.all_ensembles]
print 'cc.radius:', [ens.radius for ens in model.cc.all_ensembles]

# branch spaopt-v4
import nengo
import nengo.spa as spa
model = spa.SPA()
with model:
    model.a = spa.State(6, subdimensions=2, represent_identity=False)
    model.b = spa.State(6, subdimensions=3)    
    model.c = spa.Compare(6)
    model.cc = spa.Bind(6)
print 'a.radius:', [ens.radius for ens in model.a.all_ensembles]
print 'b.radius:', [ens.radius for ens in model.b.all_ensembles]
print 'c.radius:', [ens.radius for ens in model.c.all_ensembles]
print 'cc.radius:', [ens.radius for ens in model.cc.all_ensembles]

# branch spa-improve-defaults
import nengo
import nengo.spa as spa
model = spa.SPA()
with model:
    model.a = spa.State(6, subdimensions=2)
    model.b = spa.State(6, subdimensions=3, represent_identity=True) 
    model.c = spa.Compare(6)
    model.cc = spa.Bind(6)
print 'a.radius:', [ens.radius for ens in model.a.all_ensembles]
print 'b.radius:', [ens.radius for ens in model.b.all_ensembles]
print 'c.radius:', [ens.radius for ens in model.c.all_ensembles]
print 'cc.radius:', [ens.radius for ens in model.cc.all_ensembles]    
```

**Where should a reviewer start?**
The technical changes is just a single commit.  However, it will have many effects on spa models.

**How long should this take to review?**
This is a small change, but I expect a lot of discussion, and the biggest issue is how it impacts existing models.
- Lengthy (more than 150 lines changed or changes are complicated)

**Types of changes:**
- Breaking change (fix or feature that causes existing functionality to change)

**Checklist:**
- [x] I have read the **CONTRIBUTING.rst** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have included a changelog entry.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Still to do:**
- [ ] look at tests that should be changed (from #941 )

### CODE REVIEW

**Comment by tcstewar** [comment]
Note: I have no idea whether this PR is something we should do or not, but I'd like to have that discussion independently of #941 .

**Comment by tcstewar** [comment]
Another option for this PR would be to leave the defaults as they are, and add a helper function to change these radii.

**Comment by xchoo** [comment]
Hmmm. Two comments:
1. The 3.5 scale factor? It only works with a subdimension of 1. You can approximate the correct scaling factor using the code here: https://github.com/xchoo/spaun2.0/blob/master/_spaun/_spa/utils.py

2. Can you also include the radius scaling for the thalamus channel ensemble array (and possibly add a flag to enable the `represent_identity` as well)?

**Comment by tcstewar** [comment]
Given the discussion in the nengo dev meeting, current consensus is that we should move all this sort of stuff to a separate ```nengo_spa``` branch, leaving the current ```nengo.spa``` stuff as it is in the core repository for legacy applications.  Further developments of ```nengo.spa``` should be limited to bug fixes (and perhaps adding features to ```nengo.spa.SemanticPointer``` and ```nengo.spa.Vocabulary```, which are likely to be used by ```nengo_spa``` and other repositories.

In the future, if/when we find good ways of handling the dependencies with ```nengo_gui``` and with the various published tutorials, we can remove ```nengo.spa``` from core ```nengo``` if we feel it will make things cleaner.

**Comment by jgosmann** [comment]
I'm closing this PR because
* this will not be implemented in core Nengo to keep legacy SPA models working.
* the new nengo_spa uses intercept and evaluation point distributions which effectively provide these changed defaults (in a better way) for spaopt and thus requires no optimization step

See
* nengo/nengo_spa#4
* https://github.com/ctn-waterloo/internal_tech_reports/blob/master/The%20influence%20of%20the%20intercept%20distribution%20on%20representation%20in%20the%20NEF.ipynb

**Pull request closed without merging**
