### PR TITLE
Run only simulator tests for non-reference sim.

### PR DESCRIPTION
**Pull request by jgosmann**
Addresses nengo/nengo_ocl#65

### CODE REVIEW

**Comment by hunse** [comment]
Works as advertised. LGTM.

**Comment by tbekolay** [comment]
Cool cool... since this isn't end user facing it doesn't seem like it needs a changelog entry, but I wonder if we should start a backend-developer-specific changelog? Or is that too much for now?

**Comment by hunse** [comment]
> I wonder if we should start a backend-developer-specific changelog? Or is that too much for now?

I would say too much for *right* now, but it is something we should talk about. It might also be different for backend developers that use the builder (like me) versus those that don't. I guess those could be different sections in the backend changelog. I put it on the schedule for tomorrow!

**Comment by tbekolay** [comment]
Sounds good. Merging.

**Comment by tbekolay** [comment]
Ah, another thing that just came to mind... this will skip tests marked as `RefSimulator`, which I believe should be tested for Nengo OCL, but not other simulators. I'll make an issue to discuss how that should be handled.

**Comment by jgosmann** [comment]
For clarification, you are saying that the `RefSimulator` tests should be run with the `nengo_ocl.Simulator`?

**Comment by tbekolay** [comment]
Yes, that was my intention with the `RefSimulator` fixture: it's for simulators that use the same build process as the reference simulator, and should be doing step functions essentially the same way.

**Comment by jgosmann** [comment]
I suppose we can slightly change the logic in this PR and don't remove test items that use `RefSimulator` if it has been set to something else.

**Comment by tbekolay** [comment]
I'm doing that now. The logic is more complicated than it seems, but I'm almost done.

**Comment by tbekolay** [comment]
OK, pushed 93082065419778d7 which rewrites the `pytest_collection_modifyitems` function to correctly handle the 4 cases, and hopefully be more understandable... the logic is confusing even with the overly verbose variable names, but I think mostly makes sense with the rewrite.

In any case, with the minor changes pushed in https://github.com/nengo/nengo_ocl/pull/65 I ran the tests for the four possible conditions, and the right number of tests appear to be skipped:

1. Neither `--simulator` nor `--ref-simulator` passed: 38 tests skipped (runs all tests, frontend and backend)
2. `--simulator` but not `--ref-simulator` passed: 435 tests skipped (runs only tests with `Simulator` fixture)
3. `--ref-simulator` but not `--simulator` passed: 646 tests skipped (runs only tests `RefSimulator` fixture)
4. Both `--simulator` and `--ref-simulator` passed: 420 tests skipped (runs only tests with either `Simulator` or `RefSimulator` fixture)

**Comment by jgosmann** [comment]
At least for the `compare` tests there was a reason to delete them completely from the list of collected test. Without deleting them there is basically no way to run "all" tests, there will always be tests skipped. With removing `compare` tests, it is possible to get no skipped tests and quickly check that all relevant tests were run. (`compare` tests do not test so much that everything is working correctly, but compare performance of different versions and require more interaction anyways.)

I guess for `--simulator` and `--ref-simulator` this is not as clear, but here my line of reasoning was if these are run within the test suite of another backend, I want the skipped number of the end also to reflect the actual relevant tests to this backend.

Also, if we are going for just skipping, it might make more sense to merge `pytest_collection_modifyitems` with `pytest_runtest_setup` to have all the code handling skipping in one place.

**Comment by hunse** [comment]
I'm not sure if `RefSimulator` tests should be tested with `nengo_ocl`. At least, I haven't been running them and some of them fail right now. We use it for some cache tests, which maybe we should fix, but also for some actual simulator tests (`test_builder.py:test_commonsig_readonly`) and a custom process test (`test_processes.py:test_time`). Maybe we should just hard-code these last two tests to use `nengo.Simulator`, and fix up the cache stuff?

**Comment by tbekolay** [comment]
> Without deleting them there is basically no way to run "all" tests, there will always be tests skipped.

Ah, okay. The confusing thing for me was that regardless of whether these tests are removed or skipped, they show up in the number of tests collected, so I would run the test suite and regardless of the options, pytest would say that it collected the same number of tests. But it's true that those tests wouldn't show up in the list of tests run / skipped / failed, so I can see that as being preferable. I'll switch it back.

> I'm not sure if RefSimulator tests should be tested with nengo_ocl

I'm OK with removing the RefSimulator if it isn't useful for nengo_ocl! Presumably OCL should have some internal tests that aren't in the Nengo test suite, so if we duplicate a few tests that's no big deal.

**Comment by hunse** [comment]
We *can* do the RefSimulator tests, it's just that when we introduced it we replaced *all* instances of `nengo.Simulator`. I see three classes of tests: 

1. Those that test the reference simulator specifically
2. Those that test the reference builder (with any backend that uses the reference builder, like `nengo_ocl`)
3. Those that test general backend functionality (with the `Simulator` fixture)

Right now, we're trying to lump 1 and 2 together with `RefSimulator`, and that's not going to work. I'd move to having three fixtures corresponding to these three cases. What should we call them? Either that, or have `RefSimulator` deal with case 2 and have any tests falling under case 1 just hard-code `nengo.Simulator`.

(I guess a fourth class of tests is those that test API stuff and don't require a Simulator at all, but those aren't pertinent to this discussion).

**Comment by hunse** [comment]
I think this is good to go. Those two tests that don't work in Nengo OCL can just be skipped, since I just added a little commit that allows that.

**Comment by hunse** [comment]
@tbekolay, why did you mark it as "needs changes" before? I just want to make sure there's not something else here I'm missing.

**Comment by tbekolay** [comment]
I think the remaining issue is whether we should be skipping these tests (which my commit did) or just removing them from the set of collected tests (which was the previous behavior).

Brief summary of discussion above:

Skipping: I didn't like the disparity between the number of collected tests and those that actually get included in the pass/skip/fail report; and I like that skipped tests give you a reason why they were skipped.

Removing: Jan doesn't like that there will always be tests skipped since some options are mutually exclusive. Also for options like `compare`, the usual tests being skipped is irrelevant, and you want to be able to ensure that all `compare` tests are being run.

**Comment by hunse** [comment]
Is it possible to have them not collected, but have a flag for a "collection report" that would list every test that was not collected and why? Maybe that's getting too complicated.

For Nengo OCL, I'd like to not collect tests that are completely irrelevant. There are a number of tests that are relevant that I skip myself because I don't support those features yet, and I'd like to keep that the set of skipped tests for OCL. Otherwise, I'll have tons of skipped irrelevant tests and it will be hard to see the skipped relevant ones.

**Comment by jgosmann** [comment]
> Is it possible to have them not collected, but have a flag for a "collection report" that would list every test that was not collected and why? Maybe that's getting too complicated.

Probably, but probably complicated.

**Comment by hunse** [comment]
Okay, I've added a commit that properly names items so that backends can skip them as before (as discussed in nengo/nengo_ocl#65). I put it here because I feel like it fits well and it's small, but I can break it out into a separate PR if desired.

Any further thoughts on skipping versus not collecting? I had previously said I was in favour of not collecting, but I just realized that backends will usually xfail unsupported tests rather than skip them. So it should still be possible to tell them apart. So I have no strong opinion either way on skip versus not collect.

**Comment by tbekolay** [comment]
I think for me I like the transparency of knowing that I'm seeing all the tests, and it doesn't bother me even if a ton are skipped. I also feel like skipped tests help with discoverability; people can look at the skipped reasons and see that "compare" tests weren't requested, which could get them interested in how the compare tests work. With tests that are removed, one might never realize that those other tests exist. I also am not quite sure how to distinguish between which tests should be outright removed and which should be just skipped, as we do skip slow tests by default rather than removing them.

I'll also move the skipping stuff to `pytest_runtest_setup` to keep it all in one place (if consensus is to remove it it's easy to move it back).

**Comment by tbekolay** [comment]
OK, made a commit moving it. Here's what I get with the new commit:

```bash
$ py.test -rs
...
=========================== short test summary info ============================
SKIP [33] /Users/Trevor/Code/nengo/nengo/conftest.py:268: slow tests not requested
SKIP [5] /Users/Trevor/Code/nengo/nengo/conftest.py:270: compare tests not requested
SKIP [2] /Users/Trevor/Code/nengo/nengo/conftest.py:289: plots not requested
SKIP [2] /Users/Trevor/Code/nengo/nengo/conftest.py:289: logs not requested

=================== 689 passed, 42 skipped in 189.15 seconds ===================
```

```bash
$ py.test -rs --noexamples
...
=========================== short test summary info ============================
SKIP [17] /Users/Trevor/Code/nengo/nengo/conftest.py:268: slow tests not requested
SKIP [5] /Users/Trevor/Code/nengo/nengo/conftest.py:270: compare tests not requested
SKIP [2] /Users/Trevor/Code/nengo/nengo/conftest.py:289: plots not requested
SKIP [88] /Users/Trevor/Code/nengo/nengo/conftest.py:266: examples not requested
SKIP [2] /Users/Trevor/Code/nengo/nengo/conftest.py:289: logs not requested

================== 617 passed, 114 skipped in 104.76 seconds ===================
```

```bash
$ py.test -rs --simulator=nengo_ocl.Simulator
=========================== short test summary info ============================
SKIP [2] /Users/Trevor/Code/nengo/nengo/conftest.py:289: plots not requested
SKIP [1] /Users/Trevor/Code/nengo/nengo/conftest.py:289: logs not requested
SKIP [5] /Users/Trevor/Code/nengo/nengo/conftest.py:270: compare tests not requested
SKIP [15] /Users/Trevor/Code/nengo/nengo/conftest.py:276: RefSimulator not overridden
SKIP [33] /Users/Trevor/Code/nengo/nengo/conftest.py:268: slow tests not requested
SKIP [389] /Users/Trevor/Code/nengo/nengo/conftest.py:272: frontend tests not run for alternate backends

======= 269 passed, 445 skipped, 17 xfailed in 139.21 seconds =======
```

```bash
$ py.test -rs --ref-simulator=nengo_ocl.Simulator
=========================== short test summary info ============================
SKIP [289] /Users/Trevor/Code/nengo/nengo/conftest.py:280: Simulator not overridden
SKIP [5] /Users/Trevor/Code/nengo/nengo/conftest.py:270: compare tests not requested
SKIP [389] /Users/Trevor/Code/nengo/nengo/conftest.py:272: frontend tests not run for alternate backends
SKIP [33] /Users/Trevor/Code/nengo/nengo/conftest.py:268: slow tests not requested

=============== 15 passed, 716 skipped in 4.14 seconds ================
```

```bash
$ py.test -rs --simulator=nengo_ocl.Simulator --ref-simulator=nengo_ocl.Simulator
=========================== short test summary info ============================
SKIP [33] /Users/Trevor/Code/nengo/nengo/conftest.py:268: slow tests not requested
SKIP [5] /Users/Trevor/Code/nengo/nengo/conftest.py:270: compare tests not requested
SKIP [2] /Users/Trevor/Code/nengo/nengo/conftest.py:289: plots not requested
SKIP [389] /Users/Trevor/Code/nengo/nengo/conftest.py:272: frontend tests not run for alternate backends
SKIP [1] /Users/Trevor/Code/nengo/nengo/conftest.py:289: logs not requested

======= 284 passed, 430 skipped, 17 xfailed in 135.89 seconds =======
```

Note that the OCL tests didn't necessarily pass; I'm showing the output one would get if they all passed (OCL doesn't work on this comp).

**Comment by jgosmann** [comment]
> Is it possible to have them not collected, but have a flag for a "collection report" that would list every test that was not collected and why? Maybe that's getting too complicated.

If we go with the skip solution. Maybe we can count how many tests should be run to get the complete set of relevant tests (e.g. excluding compare tests or frontend tests) and print that number? That might be a lot easier.

**Comment by tbekolay** [comment]
Are you suggesting something that prints a more detailed summary of the
tests collected to the console right after collection? Something like
`Running 637/655 frontend tests` etc? That would be great

**Comment by jgosmann** [comment]
Something like (can still work on the exact formulation):
```Total of XXX runnable tests (excluding compare tests).```
For compare tests:
```Total of XXX runnable tests (excluding non-compare tests).```
For alternate simulator:
```Total of XXX runnable tests (excluding compare tests and front-end tests).```

And maybe a line if all runnable tests have been run (easier to check for than comparing the number of tests):
`All runnable tests were run.`

**Comment by hunse** [comment]
I agree, that would be nice. Can we bust that out into an issue so we don't delay this PR?

**Comment by jgosmann** [comment]
Sure.

**Comment by hunse** [comment]
@jgosmann, @tbekolay: If you both give me a thumbs-up, then I'll merge this. The two new commits that need checking are 90c0af9 and 3905566.

**Comment by tbekolay** [comment]
Changes look good to me. Just gotta make sure 3905566f3f2db3e4 is squashed into 93082065419778 which might cause some conflicts... I can do the history mangling if you want!

**Comment by jgosmann** [comment]
LGTM too, that one comment aside
:cake:

**Comment by hunse** [comment]
@tbekolay: Yeah, remangle everything yourself! :)

**Comment by tbekolay** [comment]
Mmm, thanks, mangling git history is a nice stress reliever ;) Will do so once we agree on a name for that method.

**Comment by tbekolay** [comment]
OK, history mangled, looks good to merge IMO!

**Pull request merged**
