### PR TITLE
Updated getting_started.rst

### PR DESCRIPTION
**Pull request by celiasmith**
Put some references to the GUI in getting started docs.

### CODE REVIEW

**Comment by Seanny123** [comment]
Looks like a good start until we get around to reviewing the entire documentation in light of the new GUI.

**Comment by tbekolay** [comment]
I think if we do want to add this in, then we should at least put in a link to the GUI's Github page. That said, I'm not sure if it's worth putting these two GUI pointers if they're the only pointers to it... I think ideally I'd prefer we move the Getting Started doc to a more general location that can point to the various subprojects.

**Comment by Seanny123** [comment]
You mean like Nengo.ca?

**Comment by tbekolay** [comment]
Sure, yeah.

**Comment by Seanny123** [comment]
So are you thinking of making it have it's own page? Because right now, it's kind of awkwardly burried in the documentation folder on Nengo.ca. Alternatively, do you want to clean up the Overview page and insert it at the end of that?

**Comment by tbekolay** [comment]
I think the Overview page is right place. I'm not sure we can just copy/paste this in though, as this page wasn't written with the GUI in mind, hence why it feels weird to me to put a few GUI references in there... it'd might need to be rewritten with the GUI in mind. So perhaps that could be the start of the GUI docs, which we could point to instead?

Ideally I'd like to move away from the Drupal site, as it's not very transparent as to what information is there and how to edit it. That'll take a fair bit of time/effort though.

**Comment by Seanny123** [comment]
This discussion seems to escaping the scope of the original issue, so I've marked as discussion and we can deal with it at the next Nengo dev meeting.

**Comment by tbekolay** [comment]
+1 SGTM :)

**Comment by Seanny123** [comment]
I just chatted a bit with @tcstewart and he thinks that switching to Jekyll is worth it, based on the increased security (no more hacks) and stability (no more hosting our own server). I agree with his assessment. 

@tbekolay if you would be so kind as to find a template, I could do the brain dead work of transferring the material 

Actually, maybe before we do that, would you like to have a chat about what functionality you want in the website initially and in the future? We could create a type of road map,  per se.

What do you think?

**Comment by jgosmann** [comment]
The last comment on this PR is more than two years old. Is this still something that should eventually be merged or can we close this PR?

Note that [this page](https://www.nengo.ai/users.html) was created in the meantime.

**Comment by tbekolay** [comment]
Agreed, the new [user guide](https://www.nengo.ai/users.html) obsoletes this PR. Sorry Chris!

**Pull request closed without merging**
