### PR TITLE
Update links to examples in README.rst

### PR DESCRIPTION
**Pull request by seankmartin**
**Motivation and context:**
The links in README.rst to the examples were broken links. I have replaced those links.

**How has this been tested?**
Clicking each of the modified links to see if they now point to the correct webpage.

**How long should this take to review?**
- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**
- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [ ] I have included a changelog entry.
- [ ] I have added tests to cover my changes.
- [ ] I have run the test suite locally and all tests passed.

I have not ticked the last three boxes as I don't think this small change is big enough to warrant appearing in a changelog. Also, I have not changed any code, so I didn't add test cases or run the test suite.

### CODE REVIEW

**Comment by hunse** [comment]
Hi @seankmartin, thanks for your contribution! I see you've checked that you've read the [Contributor's agreement](https://www.nengo.ai/caa/); could you please make a PR to add your name to the [contributor's list here](https://github.com/nengo/nengo.github.io/blob/master/people.md)? Unfortunately, we can't merge your PR until that's done.

**Comment by seankmartin** [comment]
Hi @hunse, thanks for your message :) I am very sorry, I didn't notice that I had to add my name to the contributor's list, I have now made a pull request for this here https://github.com/nengo/nengo.github.io/pull/107. Thank you very much

**Comment by drasmuss** [comment]
Added a fixup for the anaconda link in the readme (which was also out of date), as well as an unrelated link in `utils/cache.py` which would randomly go down enough to be inconvenient.

**Review by drasmuss — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request merged**
