### PR TITLE
Fixed SPA support typo and added test

### PR DESCRIPTION
**Pull request by Seanny123**
Fixed Aaron's typo as mentioned in #785 .

### CODE REVIEW

**Comment by arvoelke** [comment]
LGTM. I think the commit message should be more verbose, like: "Fixed SPA support typo and added test".

**Comment by Seanny123** [comment]
@arvoelke in an effort to rename my commit I seem to have created four additional commits. I tried resetting the head to the first commit, but that didn't work. Any suggestions on how to just keep the first commit and rename it? I've really shot myself in the foot with `git`.

**Comment by arvoelke** [comment]
I'm bad with this kind of stuff. @tbekolay is probably the one to ask. 

That said, I think doing an interactive rebase (`git rebase -i master`) is the way to go? That lets you rewrite history, since it works by re-applying your commits onto some base. You can also `squash` away your extra commits as a part of the rebase. 

If you've really messed up the history, it may just be easier to start fresh again (copy-paste the changes) and force (`-f`) push to this remote branch.

Thanks for doing this btw.

**Comment by Seanny123** [comment]
I fixed the message, but now it looks like Travis authored it. Which I guess is okay? I think it's ready to merge.

**Comment by tbekolay** [comment]
If you want to fix the author, you can amend that commit, which is something that I often do for commit messages that could use more detail.

If you're on the `fix-invert-check` branch and do `git commit --amend`, then the current commit's message will pop up for you to change. If you do `git commit --reset-author`, it will pop up the commit message, but you'll noticed in the comment block below that git will use your information for the author string (by reading what you have defined in `git config user.name` and `git config user.email`).

**Comment by Seanny123** [comment]
Thanks Trevor. Fixed it now. You can merge.

Git is literally the hardest part of programming.

**Comment by tbekolay** [comment]
Hardest, but best! ;) I dare you to attempt to navigate through the old Nengo 1.4 SVN history...

**Comment by jgosmann** [comment]
Yeah, once you master git it's awesome (and accept its mannerisms). :sunglasses:

**Pull request merged**
