### PR TITLE
Fix networks

### PR DESCRIPTION
**Pull request by hunse**
Some minor fixes to EnsembleArray and Product. The first commit removes an unused node in Product, and allows any iterable of functions to be used in `EnsembleArray.add_output`.

The second commit might be a bit more controversial. It just removes the passthrough input nodes in Product and replaces them with ObjViews.

### CODE REVIEW

**Comment by tcstewar** [comment]
Nifty...  I'm cautiously in favour of replacing passthrough input nodes with ObjViews.  Can anyone think of any loss of functionality here?  I assume we can still do prod.A.size_in and prod.A.size_out.  And even the user interface stuff should be able to detect ObjViews and visually display them similarly to PassthroughNodes, if we decide we want that....

**Comment by tbekolay** [comment]
It never occurred to me to replace passthrough nodes with ObjViews, but to me it seems like a great idea! In my mind it seems like passthrough nodes are more flexible, but I can't actually come up with a good use case of passthrough nodes that couldn't be done with ObjViews instead. If we choose to go this way, could we get rid of passthrough nodes in general? That would mean that it's no longer necessary to optimize them out on any backend.

**Comment by tbekolay** [comment]
I think I forgot about the fact that nodes can project to multiple objects, while objviews can only project to one. Probably can't get rid of them completely, but I think it's good to favour objviews when possible.

**Comment by hunse** [comment]
I think we still need passthrough nodes for e.g. the output of an EnsembleArray, because that requires multiple connections.

**Comment by tcstewar** [comment]
> I think I forgot about the fact that nodes can project to multiple objects, while objviews can only project to one.

Yikes...  really?  So what happens if I do this?

```python
model = nengo.Network()
with model:
    a = nengo.Ensemble(100, 3)
    a0 = a[0]
    a1 = a[1]
    a2 = a[2]
    
    nengo.Connection(a0, a1)
    nengo.Connection(a0, a2)
    nengo.Connection(a1, a2)
    nengo.Connection(a1, a0)
    nengo.Connection(a2, a0)
    nengo.Connection(a2, a1)
```

**Comment by tbekolay** [comment]
No, I mean you can't make an ObjView that will project to two separate objects. I.e.,

```python
a = nengo.Ensemble(100, 3)
b = nengo.Ensemble(100, 3)
c = a[0] + b[0]
nengo.Connection(a, c)
```
Though you can of course do this with nodes.

**Comment by tcstewar** [comment]
> No, I mean you can't make an ObjView that will project to two separate objects.

Ah, got it...  very good point.

**Comment by tbekolay** [comment]
Reminder to @tcstewar : check this out in the GUI

**Comment by Seanny123** [comment]
Did the Product network segment of this pull request become obsolete because of Jan's new Product network that's now merged in to `master`?

**Comment by tcstewar** [comment]
> Reminder to @tcstewar : check this out in the GUI

Right now in the GUI this is a little confusing, in that the GUI doesn't know about ObjView objects, so they don't show up.  I think it would be possible to add a new handler in the GUI for ObjView objects (in addition to Networks, Nodes, and Ensembles), if we decide we want to do this sort of thing.  One complication is it would also mean a new sort of Connection, since we'd want to draw a line between the ObjView and whatever object it's a view on.  But that's doable, if we decide we want this.

That said, there's one important functionality problem I just realized right now: you can't do a slice off an ObjView.  So right now, this change loses functionality, as you can no longer slice into ```prod.A``` or slice out of ```prod.output```.  That's a pretty important thing to be able to do.  But it would also be a pretty easy thing to add to an ObjView, I think.

> Did the Product network segment of this pull request become obsolete because of Jan's new Product network that's now merged in to master?

Yup, it's now obsolete.  However, even with the new approach, there's still the question of whether we should use passthrough nodes or ObjViews.  Right now, though, given the lack of ability to do slices on ObjViews, I'd definitely stick with passthrough Nodes.

**Comment by Seanny123** [comment]
In that case, should I take the EnsembleArray modification, delete the rest and mark for merge?

**Comment by tcstewar** [comment]
> In that case, should I take the EnsembleArray modification, delete the rest and mark for merge?

Yup, that sounds right to me.

**Comment by Seanny123** [comment]
@tcstewar made the change, ready to merge

**Comment by tcstewar** [comment]
Looks fine to me.  :)

**Comment by tbekolay** [comment]
> there's still the question of whether we should use passthrough nodes or ObjViews

Are there other networks where this is a possibility? In `Product` we have a transform on the connection now, so it's not possible, but it'd be good to look at other networks to see if that's a possibility.

In any case, made #818 to add the ability to slice ObjViews. I'll merge this now.

**Pull request merged**
