### PR TITLE
Refactor test_examples.py

### PR DESCRIPTION
**Pull request by tbekolay**
Opting for standard test functions, rather than pytest hooks. This should make this file more readable, and a tiny bit easier to add new slow tests. This also uses the `slow` mark rather than manually calling `pytest.skip`, which means that the skip reason will be the same as other slow tests.

### CODE REVIEW

**Comment by jgosmann** [comment]
Maybe rename `_test_noexceptions` to `assert_noexceptions`? That doesn't require the awkward `_` and won't be confused with an actual test function.

**Comment by tbekolay** [comment]
Good call, will do!

**Comment by tbekolay** [comment]
Done!

**Comment by jgosmann** [comment]
LGTM :cake:

**Pull request merged**
