### PR TITLE
Miscellaneous fixes

### PR DESCRIPTION
**Pull request by tbekolay**
These are a small collection of things that I changed while working on the Frontiers paper. The only user facing change, I believe, is the `Config.configures` change, so it has a changelog entry associated with it.

If any of these things are controversial, I'm happy to spin it into its own PR.

### CODE REVIEW

**Comment by tbekolay** [comment]
FYI I have no idea why TravisCI is borking on the builds for NumPy < 1.9. I made [an issue with Conda](https://github.com/conda/conda-recipes/issues/420) to see if they have any insight.

**Comment by hunse** [comment]
> FYI I have no idea why TravisCI is borking on the builds for NumPy < 1.9.

Yeah, they must have changed something on their end. The build also failed for #816 after you squashed it, and it wasn't failing before, so I'm quite sure it's not us.

**Comment by hunse** [comment]
Yeah, this all looks good.

**Comment by Seanny123** [comment]
LGTM too.

**Comment by tbekolay** [comment]
OK, I amended that commit so it adds things to `strings.ipynb`, and normalizes the Operator strings quite a bit (28704ecf0ba45b720f7d9998e62af09a87cf3d6e). I also added d8dc25b5e472683c1233a922157bed35d1914aed which includes `__repr__`s for learning rules that are printed in `strings.ipybn` while I was at it. I made sure not to add synapes and other things that I know @hunse added in #758 though!

**Comment by hunse** [comment]
Looks good! I added a little fix to make the list of operators in `strings.ipynb` slightly more legible.

Also, you reminded me that learning rule types should also be frozen objects. I forgot to include them in #758.

**Comment by hunse** [comment]
If that fixup looks good to you, @tbekolay, I'll merge.

**Comment by tbekolay** [comment]
Yep, looks good to me!

**Pull request merged**
