### PR TITLE
New processes for convnets

### PR DESCRIPTION
**Pull request by hunse**
I've added a couple new Processes to facilitate running convnets in Nengo, namely one for 2D convolution with a filterbank and one for presenting a series of inputs each for a fixed length of time.

I've also added a seed for random processes, as requested in #787.

This PR is based off the `frozen` branch (see #758).

### CODE REVIEW

**Comment by Seanny123** [comment]
Btw, this pull request is failing tests, but luckily only for Python 3.

**Comment by hunse** [comment]
Yeah it's waiting on dependencies anyway.

**Comment by hunse** [comment]
So we talked about putting this stuff in a separate repository. Any suggestions on whether we should have one repository (`nengo_extra` or something) that has lots of stuff like this, or have a specific one for this stuff?

**Comment by tbekolay** [comment]
Hmm, perhaps these would fit well in [`nengo_deeplearning`](https://github.com/nengo/nengo_deeplearning)? Or a more general `nengo_machinelearning`? Ultimately it's up to you, if you want to have convnet stuff in a specific repo for a while that's cool, it can always be moved to a repo with more other stuff in it later on down the line.

**Comment by hunse** [comment]
I didn't know such a repository existed! That does look like a good place, though ultimately these are a bit more general than just deep learning or machine learning. For example, the `PresentInput` process is useful for any network you want to present a series of inputs to, and `Conv2` could be used with hand-designed Gabor filters as easily as filters that have been learned. But I can put them there for now, as long as people aren't tricked by the name.

**Comment by tbekolay** [comment]
Hmm, `PresentInput` we might want to merge in `nengo`, actually, seems pretty useful. The others maybe in `nengo_deeplearning`. What do you think?

**Comment by hunse** [comment]
Yeah, I'm fine with that. There will have to be a supporting PR for this stuff anyway, since I add a few parameters and some features to Process. So I'll throw PresentInput in there too.

**Comment by tbekolay** [comment]
Great, sounds good! :rainbow:

**Comment by hunse** [comment]
Moved to nengo/nengo_deeplearning#3

**Pull request closed without merging**
